### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by xmxstudio** [PixelogicDev/FocusBlock#20]
- User can enter blank title
- User can enter custom unchecked time. (e.g., -10, 0, 111111111111111111111111)
- When editing focus block title. pressing enter defaults to delete prompt. bad UX
- When time is too great, countdown timer does not work when clicking get focused

https://focusblock.stream/dashboard/ByiZCdsfm

**Comment by xmxstudio** [comment]
https://focusblock.stream/dashboard/****enterAnything
https://focusblock.stream/404pagehandlerneeded

**Comment by adilanchian** [comment]
@xmxstudio I updated your bug with some formatting :)

@frubesss Thanks so much for getting these commits in! Would you be able to check off the fixes you have made so far? I am excited to see your PR!

**Comment by frubesss** [comment]
@adilanchian Hi, just working through all these bugs while I have a bit of downtime. 

Will have explanations to my reasoning behind these changes with the pull request. 

I can't tick the tasks off in the original post as I don't have edit permissions. 

Thanks

**Comment by adilanchian** [comment]
Hey @frubesss,

Thanks for the heads up and no worries at all! Glad to see you are adding some dope fixes. No worries about the list, I will go ahead and change that.

**Comment by adilanchian** [comment]
MERGED! Thanks for all the work :)
