### ISSUE TITLE
Get focused button unresponsive on firefox quantum

### ISSUE THREAD

**Issue by SB-FM** [PixelogicDev/FocusBlock#21]
The **Get Focused** button on focusblock.stream appears to be unresponsive on Firefox Quantum. Clicking it does not redirect to dashboard. Also doesn't throw an error in the console.

Disabled all addons and still experience that behavior. 

Firefox Quantum Version  61.0.1 (64bit)

**Comment by lukeberry99** [comment]
This is because the `<Link>` is inside a button, and the buttons click event is taking precedence over the `<Link>`

**Comment by adilanchian** [comment]
^^ Yup @lukeberry99 thats exactly right! stupid mistake on my end haha. Would you or @SB-FM want to make a quick fix for this? Would love to get this fixes!

**Comment by adilanchian** [comment]
This has been fixed and committed directly to `release-1.0.1`
