### ISSUE TITLE
We picked Vue, now let's discuss the setup

### ISSUE THREAD

**Issue by kocisov** [PixelogicDev/FocusBlock#8]
We have a few options
1. We can use **Parcel** https://parceljs.org/
2. We can use **Vue CLI** or Vuepack? https://github.com/vuejs/vue-cli
3. We can make our own **Webpack** configuration for **Vue**

**Comment by adilanchian** [comment]
Thank you @Kocisov for the issue! We have decided to go Vue CLI :)
